FROM node:20-bookworm

# set user as default sudo-enabled user
ARG USERNAME=node
RUN apt-get update \
  && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME
USER $USERNAME

RUN sudo apt-get update && sudo apt-get install -y python3 make g++ libxi-dev libglu1-mesa-dev libglew-dev
RUN sudo ln -s /usr/bin/python3 /usr/bin/python
RUN sudo rm -rf /var/lib/apt/lists/*
