FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y python3 make g++ libxi-dev libglu1-mesa-dev libglew-dev
COPY requirements.txt .
COPY config.txt.docker ./config.txt
COPY ./dose3d_commons /app/dose3d_commons
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app/backend
