# Phase 2: build backend image
FROM python:3.11

WORKDIR /app

# Copy python files
COPY requirements.txt .
COPY config.txt.docker ./config.txt
COPY ./dose3d_commons /app/dose3d_commons
RUN pip install --no-cache-dir -r requirements.txt

# Envs
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app/backend
