#include <iostream>
#include <random>
#include <filesystem>
#include <fstream>
#include <unistd.h>

using namespace std;

int main(int argc, char **argv) {
    string out_dir;

    cout << "Hello, World!" << endl;
    cout << "I'm dummy Dose3D and generate dummy data only for WebInterface test" << endl;
    cerr << "And generate dummy error to stderr :)" << endl;

    cout << "Start parameters:" << endl;
    for (int i = 0; i < argc; i++)
    {
        cout << "argv[" << i << "]: " << argv[i] << endl;

        // save out_dir if "-o" parameter provided and is not latest parameter
        if (string(argv[i]) == "-o")
        {
            if (i + 1 < argc)
            {
                out_dir = argv[i + 1];
            }
        }
    }

    auto out_file = filesystem::path(out_dir) / "run-0-analysis.root";
    cout << "Output file: " << out_file << endl;

    random_device rd;
    mt19937 mt(rd());
    uniform_real_distribution<double> dist(10.0, 100.0);
    int rand_sleep = int(dist(mt));

    cout << "Random delay (10-100s): " << rand_sleep << "s" << endl;
    for (int i = 1; i <= rand_sleep; i++)
    {
        cout << "... " << i << " sec" << endl;
        sleep(1);
    }

    ofstream sample_out;
    sample_out.open (out_file);
    sample_out << "Generated by dummy.\n";
    sample_out.close();

    return 0;
}
