services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dose3d" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=dose3d
      - POSTGRES_USER=dose3d
      - POSTGRES_PASSWORD=dose3d

  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer.frontend
    volumes:
      - ../..:/workspaces:cached
    # command: sleep infinity # does not run frontend dev server
    command: bash -c "npm start" # runs frontend dev server with hot reload
    network_mode: service:backend

  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer.backend
    command: bash -c "python manage.py migrate && python manage.py createsuperuser --noinput || true && sleep infinity" # does not run python dev server
    # command: bash -c "python manage.py migrate && python manage.py createsuperuser --noinput || true && python manage.py runserver 0.0.0.0:8000" # runs python dev server with hot reload
    volumes:
      - backend-data:/app/var
      - ../backend:/app/backend
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

volumes:
  postgres-data:
  backend-data:
