# Generated by Django 4.1.7 on 2023-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('title', models.CharField(max_length=64, verbose_name='Jobs title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Jobs description')),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('PENDING', 'PENDING'), ('DONE', 'DONE')], default='TODO', max_length=16, verbose_name='Current status')),
                ('is_error', models.BooleanField(default=False, verbose_name='Finish with errors')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ('created_at',),
            },
        ),
    ]
