# Generated by Django 4.1.7 on 2023-04-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('title', models.CharField(max_length=64, verbose_name='Jobs title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Jobs description')),
                ('status', models.CharField(choices=[('INIT', 'init'), ('QUEUE', 'queue'), ('RUNNING', 'running'), ('DONE', 'done')], default='init', max_length=16, verbose_name='Current status')),
                ('ret_code', models.BooleanField(blank=True, null=True, verbose_name='Return code of Dose3D process')),
                ('toml', models.TextField(blank=True, default='', verbose_name='Content of TOML file')),
                ('args', models.CharField(default='', max_length=255, verbose_name='Dose3D command line args')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobRootFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='File from ROOT')),
                ('size', models.IntegerField(verbose_name='File size')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnd3d.job')),
            ],
            options={
                'verbose_name': 'Root file',
                'verbose_name_plural': 'Root files',
                'ordering': ('file_name',),
                'unique_together': {('job', 'file_name')},
            },
        ),
    ]
