# Generated by Django 4.2.1 on 2023-06-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Logs file from ROOT')),
                ('size', models.IntegerField(verbose_name='File size')),
                ('is_output', models.BooleanField(default=False, verbose_name='This is logs from output of dose3d process')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnd3d.job')),
            ],
            options={
                'verbose_name': 'Logs file',
                'verbose_name_plural': 'Logs files',
                'ordering': ('file_name',),
                'unique_together': {('job', 'file_name')},
            },
        ),
    ]
