# Generated by Django 4.2.5 on 2023-09-21 08:50

from django.db import migrations, models

from tnd3d.models import WorkspaceCell


def post_migration(arg1, arg2):
    WorkspaceCell.objects.filter(type='j').update(type='r')


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacecell',
            name='type',
            field=models.CharField(choices=[('m', 'markdown'), ('r', 'root'), ('d', 'dose3d')], max_length=1),
        ),
        migrations.RunPython(post_migration),
    ]
