# Generated by Django 4.2.5 on 2023-10-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0002_alter_workspacecell_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnd3d.job', verbose_name='Job')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnd3d.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Job to workspace assign',
                'verbose_name_plural': 'Job to workspace assigns',
                'ordering': ('job',),
                'unique_together': {('workspace', 'job')},
            },
        ),
    ]
