# Generated by Django 4.2.1 on 2023-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0002_joblogfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblogfile',
            name='size',
            field=models.IntegerField(default=0, verbose_name='File size'),
        ),
        migrations.AlterField(
            model_name='jobrootfile',
            name='size',
            field=models.IntegerField(default=0, verbose_name='File size'),
        ),
    ]
