# Generated by Django 4.2.1 on 2023-06-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0003_alter_joblogfile_size_alter_jobrootfile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ret_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Return code of Dose3D process'),
        ),
    ]
