# Generated by Django 4.2.5 on 2023-11-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0003_workspacejob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspacecell',
            unique_together=set(),
        ),
    ]
