# Generated by Django 4.2.2 on 2023-06-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0004_alter_job_ret_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('title', models.CharField(max_length=64, verbose_name='Jobs title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Jobs description')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Position in workspace')),
                ('type', models.CharField(choices=[('m', 'markdown'), ('j', 'json')], max_length=1)),
                ('content', models.TextField(blank=True, default='', verbose_name='Cell content')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnd3d.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace cell',
                'verbose_name_plural': 'Workspace cells',
                'ordering': ('pos',),
                'unique_together': {('workspace', 'pos')},
            },
        ),
    ]
