# Generated by Django 4.2.5 on 2023-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0005_rootfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootfile',
            name='file_path',
            field=models.CharField(max_length=255, verbose_name='Logs file from ROOT'),
        ),
    ]
