# Generated by Django 4.2.5 on 2023-12-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0006_alter_rootfile_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='rootfile',
            name='uploaded_file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tnd3d.uploadedfile', verbose_name='Uploaded file'),
        ),
    ]
