# Generated by Django 4.2.5 on 2023-12-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnd3d', '0007_uploadedfile_rootfile_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootfile',
            name='jrf',
        ),
        migrations.AlterField(
            model_name='rootfile',
            name='uploaded_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tnd3d.uploadedfile', verbose_name='Uploaded file'),
        ),
    ]
