name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Keep connection alive
        run: while true; do echo "Still running..."; sleep 30; done &

      - name: Connect to server and deploy
        run: |
          sshpass -p "${{ secrets.TAURUS_SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 \
          ${{ secrets.TAURUS_SERVER_USER }}@${{ secrets.TAURUS_SERVER_ADDRESS }} << 'EOF'
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=60 \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -i ${{ secrets.SSH_KEY_TAURUS_PATH }} << 'EOF'
            cd ~/g4rt-webui
            git pull origin master
          EOF
